version: "3.5"

services:
  clouddistrict-php81-symfony54:
    container_name: clouddistrict-php81-symfony54
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3  config for diffents os###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
    #1000 Local port and 8000 container port
    ports:
      - "1000:8000"
    networks:
      - clouddistrict-php81-symfony54-network
    # depends_on:
    #   - clouddistrict-php81-symfony54-mysql
  database:
    # clouddistrict-php81-symfony54-mysql:
    container_name: clouddistrict-php81-symfony54-mysql
    image: mysql:8.0.26
    ports:
      - "3336:3306"
    environment:
      MYSQL_DATABASE: mysql_symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - clouddistrict-php81-symfony54-mysql-data:/var/lib/mysql
    networks:
      - clouddistrict-php81-symfony54-network
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  clouddistrict-php81-symfony54-rabbit:
    container_name: clouddistrict-php81-symfony54-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - clouddistrict-php81-symfony54-network
networks:
  clouddistrict-php81-symfony54-network:

volumes:
  clouddistrict-php81-symfony54-mysql-data:
